### ISSUE TITLE
Seeding is weird

### ISSUE THREAD

**Issue by StevenNunez** [learn-co-curriculum/flatiron-bnb-associations#2]
Seed task prevents tests for properties to run. Maybe set up seed task to run for specific association tests, so they only blow up when they need to. Also, to add clarity, seed task should set foreign keys using the instance variable's #id method, not but finding it in the Database. It's hard to reason about the associations otherwise.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by deniznida** [comment]
What @StevenNunez means here is:

1. The `rails_helper.rb` has a before do actions with seed tasks. 
2. The seed tasks, in the same file, is finding an object in the database then assigning it as a foreign key.

Solution:

1. Every rspec should create the instances it is checking for itself
![screen shot 2015-10-26 at 2 03 06 pm](https://cloud.githubusercontent.com/assets/9004428/10737891/1c5842be-7beb-11e5-8b52-ed03f22b5753.png)

2. instead of having it like this, where we find an instance in the database then assign it to a foreign key
![screen shot 2015-10-26 at 2 03 54 pm](https://cloud.githubusercontent.com/assets/9004428/10737910/2ce4b2b6-7beb-11e5-9eb6-0ac057797643.png)

We should write our spec like this, where we assign the foreign key from an instance we create in the file
![screen shot 2015-10-26 at 2 05 26 pm](https://cloud.githubusercontent.com/assets/9004428/10737917/3535d6e8-7beb-11e5-948d-eaffe78195fc.png)

**Comment by StevenNunez** [comment]
Fixed in #3
